# Generated by Django 5.1.4 on 2025-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=8, null=True)),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
